# 애플리케이션 이름 설정
spring.application.name=step10-boot-basic

# 서버 포트 설정 (기본 8080 대신 8888 사용)
server.port=8888

# Thymeleaf 설정
# 개발 시 수정사항을 즉시 확인하기 위해 캐시를 끕니다.
spring.thymeleaf.cache=false
# 파일 확장자 설정 (.html)
spring.thymeleaf.suffix=.html
# 템플릿 파일이 위치한 경로
spring.thymeleaf.prefix=classpath:/templates/
